services:
  - type: web
    name: agence-voyage
    env: python
    buildCommand: "pip install --upgrade pip && pip install Flask && pip install -r requirements.txt && pip list && which python3"
    startCommand: "/opt/render/project/src/.venv/bin/python3 app.py"
    plan: free
    branch: main
    autoDeploy: true
