
services:
  - type: web
    name: agence-voyage
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python3 app.py"
    plan: free
    branch: main
    autoDeploy: true
    
